package main

import (
	"context"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/Public/convert-tux-to-go/internal/cproc/flow"
	"github.com/Public/convert-tux-to-go/internal/cproc/ir"
	"github.com/Public/convert-tux-to-go/internal/cproc/scanner"
	"github.com/Public/convert-tux-to-go/internal/telemetry"
)

// runDiscover implements `tuxgo discover <file|dir>` — the PRD-2026-09-10
// endpoint-discovery scan-then-tag mode: the flow IR finds the API
// candidates (conditions/blocks enclosing Fget32 reads and non-error
// Fadd32 writes) and emits a mapping draft the user tags with names/routes.
// The tool never invents endpoints (§4.2.8) — the draft carries `name: ""`
// placeholders the user fills before `plan`/`convert` consume the file.
func runDiscover(ctx context.Context, args []string) error {
	log := telemetry.Log(ctx)
	fs := flag.NewFlagSet("discover", flag.ContinueOnError)
	outDir := fs.String("out", "", "Directory for the per-entry draft yamls (required for directory targets; file mode prints to stdout)")
	configPath := fs.String("config", "", "Path to .tuxgo.yaml (default: ./.tuxgo.yaml when present, else defaults)")

	flagArgs, positional := reorderArgs(args)
	if err := fs.Parse(flagArgs); err != nil {
		return err
	}
	if len(positional) == 0 {
		return fmt.Errorf("must provide a .pc/.pcf file or a directory to discover")
	}
	target := positional[0]
	if *configPath != "" {
		if _, _, err := loadRunConfig(*configPath); err != nil {
			return err
		}
	}

	fi, err := os.Stat(target)
	if err != nil {
		return fmt.Errorf("cannot access target path %s: %w", target, err)
	}
	dirMode := fi.IsDir()
	if dirMode && *outDir == "" {
		return fmt.Errorf("discover: a directory target needs -out <dir> (one draft per entry)")
	}

	irFiles, err := extractFlowIR(target)
	if err != nil {
		return err
	}
	if len(irFiles) == 0 {
		return fmt.Errorf("no .pc or .pcf files found in %s", target)
	}

	written := 0
	for _, f := range irFiles {
		if f.Entry == "" {
			fmt.Printf("- %s: no entry function (fn library) — skipped\n", filepath.Base(f.Path))
			continue
		}
		src, err := os.ReadFile(f.Path)
		if err != nil {
			return fmt.Errorf("discover: read %s: %w", f.Path, err)
		}
		facts, err := scanner.ScanBytes(src, f.Path)
		if err != nil {
			return fmt.Errorf("discover: scan %s: %w", f.Path, err)
		}
		tree := flow.Build(src, facts, f.Entry, f)
		candidates := flow.Discover(tree, f.Conditions)
		if len(candidates) == 0 {
			fmt.Printf("- %s: no API candidates found (%d conditions inspected)\n", f.Entry, len(f.Conditions))
			continue
		}
		draft := renderDraft(f, candidates, dirMode)
		if dirMode {
			base := strings.TrimSuffix(filepath.Base(f.Path), filepath.Ext(f.Path))
			path := filepath.Join(*outDir, base+".mapping.yaml")
			if err := os.MkdirAll(*outDir, 0o755); err != nil {
				return err
			}
			if err := os.WriteFile(path, []byte(draft), 0o644); err != nil {
				return fmt.Errorf("discover: write %s: %w", path, err)
			}
			written++
			log.Info("draft written", "path", path, "candidates", len(candidates))
		}
		printDiscoverSummary(f, tree, candidates)
		if !dirMode {
			fmt.Println()
			fmt.Println(draft)
		}
	}
	if dirMode {
		fmt.Printf("\n%d draft(s) written to %s — tag name/route in each, then: tuxgo convert %s -mapping %s\n",
			written, *outDir, target, *outDir)
	}
	return nil
}

// renderDraft emits the mapping draft (DIS-D5): only strict-decodable keys,
// metadata in comments, `name: ""`/`route: ""` to tag, census comments, and
// the non-candidates kept (commented) for user control.
func renderDraft(f *ir.File, candidates []flow.Candidate, dirMode bool) string {
	entry := filepath.Base(f.Path)
	svc := strings.ToLower(strings.ReplaceAll(strings.TrimSuffix(entry, filepath.Ext(entry)), "-", "_"))
	var sb strings.Builder
	fmt.Fprintf(&sb, "# %s — generated by `tuxgo discover` (PRD-2026-09-10 endpoint discovery).\n", entry)
	sb.WriteString("#\n")
	sb.WriteString("# HOW TO USE: tag every endpoint below with a Go method name and a route\n")
	sb.WriteString("# path (or delete the entries you do not want), uncomment and fill\n")
	sb.WriteString("# module/readDBs/routeGroup, then run:\n")
	if dirMode {
		sb.WriteString("#   tuxgo convert <target dir> -mapping <this draft's directory>\n")
	} else {
		sb.WriteString("#   tuxgo plan <file> -mapping <this file>\n")
	}
	sb.WriteString("# A condition you omit stays logic-only. `condition:` is the top-level\n")
	sb.WriteString("# inventory index; `conditionRef:` is a nested qualifying block.\n")
	sb.WriteString("\n")
	if dirMode {
		fmt.Fprintf(&sb, "source: %s\n", entry)
	}
	fmt.Fprintf(&sb, "service: %s                    # TODO rename (must be a valid Go identifier)\n", svc)
	fmt.Fprintf(&sb, "# module: your-app/pkg/services/%s\n", svc)
	sb.WriteString("# readDBs:                     # logical read-DB names for handler wiring\n")
	sb.WriteString("#   - EXAMPLE\n")
	fmt.Fprintf(&sb, "# routeGroup: /%s\n", svc)
	sb.WriteString("\nendpoints:\n")

	mapped := map[int]string{} // condition index → candidate key ("" when only non-candidate)
	for _, c := range candidates {
		n := strings.SplitN(strings.TrimPrefix(c.Key, "c"), ".", 2)[0]
		var idx int
		fmt.Sscanf(n, "%d", &idx)
		if _, ok := mapped[idx]; !ok {
			mapped[idx] = c.Key
		}
	}
	for _, c := range candidates {
		if strings.Contains(c.Key, ".") {
			fmt.Fprintf(&sb, "  - conditionRef: %-12s # nested block, lines %d-%d | reads: %s | writes: %s",
				c.Key, c.StartLine, c.EndLine,
				fieldsOrDash(c.Gets), fieldsOrDash(c.Adds))
			if len(c.QueryIDs) > 0 {
				fmt.Fprintf(&sb, " | queries: %s", strings.Join(c.QueryIDs, ","))
			}
			if c.Redundant {
				sb.WriteString(" | NOTE: subset of its parent — consider tagging the parent")
			}
			sb.WriteString("\n")
		} else {
			fmt.Fprintf(&sb, "  - condition: %-15s # lines %d-%d | reads: %s | writes: %s",
				strings.TrimPrefix(c.Key, "c"), c.StartLine, c.EndLine,
				fieldsOrDash(c.Gets), fieldsOrDash(c.Adds))
			if len(c.QueryIDs) > 0 {
				fmt.Fprintf(&sb, " | queries: %s", strings.Join(c.QueryIDs, ","))
			}
			sb.WriteString("\n")
		}
		sb.WriteString("    name: \"\"                  # TODO tag the Go method name\n")
		sb.WriteString("    route: \"\"                 # TODO tag the route path (starts with /)\n")
	}
	// Non-candidates, commented, for control.
	var rest []int
	for _, cond := range f.Conditions {
		if _, ok := mapped[cond.Index]; !ok {
			rest = append(rest, cond.Index)
		}
	}
	if len(rest) > 0 {
		sb.WriteString("# not API candidates by the discovery rubric — map manually if you know better:\n")
		for _, idx := range rest {
			cond := &f.Conditions[idx-1]
			gets, adds, _ := flow.Census(cond)
			fmt.Fprintf(&sb, "# - condition: %-13d # lines %d-%d | reads: %s | writes: %s\n",
				idx, cond.StartLine, cond.EndLine, fieldsOrDash(gets), fieldsOrDash(adds))
		}
	}
	return sb.String()
}

func printDiscoverSummary(f *ir.File, tree *flow.Tree, candidates []flow.Candidate) {
	top, nested := 0, 0
	for _, c := range candidates {
		if strings.Contains(c.Key, ".") {
			nested++
		} else {
			top++
		}
	}
	fmt.Printf("\n%s: %d candidate(s) (%d top-level, %d nested) from %d condition(s), coverage %d/%d lines\n",
		f.Entry, len(candidates), top, nested, len(f.Conditions),
		tree.Coverage.Classified, tree.Coverage.CodeLines)
	for _, c := range candidates {
		note := ""
		if c.Redundant {
			note = "  (redundant with parent)"
		}
		fmt.Printf("  %-8s lines %d-%d  reads %-2d writes %-2d%s\n",
			c.Key, c.StartLine, c.EndLine, len(c.Gets), len(c.Adds), note)
	}
}

func fieldsOrDash(fields []string) string {
	if len(fields) == 0 {
		return "none"
	}
	sorted := append([]string(nil), fields...)
	sort.Strings(sorted)
	return strings.Join(sorted, ",")
}
